//------------------------------------------------------------------------
// Copyright(c) 2024 Teodor Synths.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"MyPlugin.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"MyPlugin VST3 (64Bit)"
#else
#define stringFileDescription	"MyPlugin VST3"
#endif
#define stringCompanyName		"Teodor Synths\0"
#define stringLegalCopyright	"Copyright(c) 2024 Teodor Synths."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
